/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CommandRequest {
  /**
   * API version, e.g., '1.0'
   */
  version: string;
  /**
   * Request ID for correlating responses
   */
  id: number;
  /**
   * RouterOS command path + action, e.g., '/ip/address/print' or topology command
   */
  command: string;
  /**
   * Command parameters (key=value pairs)
   */
  params?: {
    [k: string]: unknown;
  };
  /**
   * Optional device ID to target. If omitted, uses the default device.
   */
  deviceId?: string;
  [k: string]: unknown;
}
