/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CommandResponse {
  /**
   * Matches the request ID
   */
  id: number;
  /**
   * Command output (text table, structured data, or null)
   */
  result?:
    | string
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | null;
  /**
   * Error message if command failed
   */
  error?: string | null;
  [k: string]: unknown;
}
